from . import mongo , db
from flask import Blueprint


data = Blueprint('data', __name__)


mongo.db.artist_data.insert_many([{
     "artist_name" : "Led Zeppelin",
     "artist_genre" : ["Hard Rock", "Blues Rock", "Folk Rock", "Heavy Metal"],
     "artist_description": "Led Zeppelin were an English rock band formed in London in 1968. The group consisted of vocalist Robert Plant, guitarist Jimmy Page, bassist/keyboardist John Paul Jones, and drummer John Bonham. With their heavy, guitar-driven sound, Led Zeppelin are regularly cited as one of the progenitors of heavy metal, although their style drew from a variety of influences, including blues and folk music.",
     "artist_members": ["Robert Plant", "Jimmy Page", "John Paul Jones", "John Bonham"],
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2012/11/LedZeppelin.jpg",
     "album_url": ["https://api.time.com/wp-content/uploads/2014/06/ledzep.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71mKCivU38L._AC_SL1200_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71whCYj9mtL._AC_SL1200_.jpg",
                    "https://www.thisdayinmusic.com/wp-content/uploads/2018/05/led-zeppelin-iv.jpg",
                    "https://cdn.mos.cms.futurecdn.net/2HZ8HfhPdzGjzxFSjjnLK5.jpg",
                    "https://img.cdandlp.com/2018/01/imgL/119046525.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71Uy9%2Bv4W8L._SL1057_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/712vB0qw1IL._AC_SL1218_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/81QZqBpmuBL._AC_SL1401_.jpg"]
   },
   {
    "artist_name": "The Beatles",
    "artist_genre":["Rock", "Pop"],
    "artist_members":["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"],
    "artist_description": "The Beatles were an English rock band formed in Liverpool in 1960. With a line-up comprising John Lennon, Paul McCartney, George Harrison and Ringo Starr, they are commonly regarded as the most influential band of all time. The group were integral to the development of 1960s counterculture and popular music's recognition as an art form.",
    "artist_icon": "https://miro.medium.com/max/12106/1*zdmpyfSSsyJbUWP3wU0onw.jpeg",
    "album_url": ["https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/PleasePleaseMe_1.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_463.jpg",
                   "https://images-na.ssl-images-amazon.com/images/I/71QKKZZABLL.jpg",
                   "https://www.popsike.com/pix/20171220/232603676076.jpg",
                   "https://www.beatlesbible.com/wp/media/canada_twist_and_shout.jpg",
                   "https://www.beatlesbible.com/wp/media/usa_beatles-second-album-960x960.jpg",
                   "https://images.genius.com/7d93682f1062d894ee6b75d9b42c519e.1000x1000x1.jpg",
                   "https://i.pinimg.com/originals/1e/44/f4/1e44f4c45fd1794b119ff5b77d214956.jpg",
                   "https://www.beatlesbible.com/wp/media/something_new-960x960.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/BeatlesForSale_1.jpg",
                   "https://www.beatlesbible.com/wp/media/usa_beatles-65.jpg",
                   "https://i.pinimg.com/originals/b8/af/f5/b8aff55f6fd9973b9e0104e4e11e2618.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_447.jpg?itok=H9p6ueVD&timestamp=1354886431",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_450.jpg",
                   "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-245574-The-Beatles-Yesterday-Today.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_449.jpg?itok=vEdbQ8AQ&timestamp=1354886431",
                   "https://images-na.ssl-images-amazon.com/images/I/91l7ue6WOhL._AC_SL1500_.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/Magical_0.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_442.jpg?itok=gJ2GzgoW&timestamp=1354886431",
                   "https://images-na.ssl-images-amazon.com/images/I/91IaG%2BLrzmL._AC_SL1500_.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_441.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_459.jpg?itok=OGwy4GrW&timestamp=1354886431"]
},
{
    "artist_name": "The Rolling Stones",
    "artist_genre": ["Rock", "Blues", "Rock and Roll"],
    "artist_members":["Mick Jagger", "Keith Richards", "Ronnie Wood", "Charlie Watts"],
    "artist_description": "The Rolling Stones were at the forefront of the British Invasion of bands that became popular in the United States in 1964 and were identified with the youthful and rebellious counterculture of the 1960s. Rooted in blues and early rock and roll, the band started out playing covers but found more success with their own material; songs such as '(I Can't Get No) Satisfaction' and 'Paint It Black' became international hits, and Aftermath (1966) – their first entirely original album – has been considered the most important of the band's formative records",
    "artist_icon": "https://static.spin.com/files/2019/11/GettyImages-113914585-1573422723-1387x1000.jpg",
    "album_url":["https://images-na.ssl-images-amazon.com/images/I/71smgDG%2BwmL._SL1400_.jpg",
                "https://merchbar.imgix.net/product/vinylized/upc/02/018771940210.jpg?w=1280&h=1280&quality=60&auto=compress%252Cformat",
                "https://img.cdandlp.com/2018/03/imgL/119086142.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71VRIposvFL._AC_SL1081_.jpg",
                "https://cdn.shopify.com/s/files/1/1110/4380/products/out_1_1024x1024.jpg?v=1469913732",
                "https://images-na.ssl-images-amazon.com/images/I/71nZ93p2r6L._SL1052_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61NRkoLaVBL._SL1050_.jpg",
                "https://img.cdandlp.com/2018/01/imgL/119037544.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1XVfdlfEpL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81oDiFJodeL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91RtFs10t2L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81nq2oxgpOL._AC_SL1417_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fLCv-HDV/SharedImage-57461.jpg?t=8e089894710294b6de51",
                "https://img.cdandlp.com/2015/12/imgL/117795678.jpg",
                "https://i0.cdn.hhv.de/catalog/shop_detail_zoom/00550/550930.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81-skWr98xL._SL1400_.jpg",
                "https://classicrockreview.files.wordpress.com/2013/03/115380777.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71FS5m9frSL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91-xbEW-OwL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81hNwsqlPxL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Azu70DcmL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Fw-KkZIzL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81kY1ASWjgL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81wZCql9M6L._AC_SL1400_.jpg",
                "https://townsquare.media/site/295/files/2015/09/Rolling-Stones-Bigger-Bang.jpeg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://townsquare.media/site/295/files/2016/11/stones1.jpg?w=980&q=75"]
},
{
    "artist_name": "Pink Floyd",
    "artist_genre": ["Pink Floyd", "Progressive Rock", "Experimental Rock"],
    "artist_members":["Nick Mason","Roger Waters","Richard Wright","Syd Barrett","David Gilmour"],
    "artist_description": "Pink Floyd were an English rock band formed in London in 1965. Gaining a following as a psychedelic pop group, they were distinguished for their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows, and became a leading band of the progressive rock genre. They are one of the most commercially successful and influential bands in popular music history.",
    "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2018/06/pink-floyd-1973-32d763d9-8deb-4cd8-a287-92ae0de7df3a.jpg",
    "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81Kzmcv5wXL._AC_SL1300_.jpg",
                "https://images.genius.com/12d2417b62f7f315f2bd8d8aea445f8a.1000x1000x1.jpg",
                "https://townsquare.media/site/295/files/2014/08/Pink-Floyd-More.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81-Joj09kIL._SL1300_.jpg",
                "https://townsquare.media/site/295/files/2015/10/Pink-Floyd-Atom-Heart-Mother.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81hBOBD242L._SL1500_.jpg",
                "https://townsquare.media/site/295/files/2012/06/Pink-Floyd-Obscured-by-Clouds-Photo.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81aTawcGdmL._AC_SL1500_.jpg",
                "https://miro.medium.com/max/1000/1*Aad3rcP6yKOj3LgWqx75gA.jpeg",
                "https://i2.wp.com/liveforlivemusic.com/wp-content/uploads/2017/01/animalspigs.jpg?fit=1920%2C1080&ssl=1",
                "https://images-na.ssl-images-amazon.com/images/I/715jbEtLNcL._AC_SL1489_.jpg",
                "https://consequenceofsound.net/wp-content/uploads/2017/06/pink-floyd-the-final-cut.jpg?quality=80",
                "https://images-na.ssl-images-amazon.com/images/I/81NuMz4OsrL._AC_SL1310_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81fvyZlrbAL._AC_SL1300_.jpg",
                "https://i.ytimg.com/vi/RFXBlS0KsHU/maxresdefault.jpg"]
},
{
    "artist_name": "Metallica",
    "artist_genre": ["Heavy Metal", "Thrash Metal"],
    "artist_members":["James Hetfield", "Lars Ulrich", "Kirk Hammett", "Robert Trujillo"],
    "artist_description": "Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist/guitarist James Hetfield and drummer Lars Ulrich, and has been based in San Francisco for most of its career. The band's fast tempos, instrumentals and aggressive musicianship made them one of the founding 'big four' bands of thrash metal, alongside Megadeth, Anthrax and Slayer. Metallica's current lineup comprises founding members and primary songwriters Hetfield and Ulrich, longtime lead guitarist Kirk Hammett and bassist Robert Trujillo. Guitarist Dave Mustaine (who went on to form Megadeth after being fired from the band) and bassists Ron McGovney, Cliff Burton (who died in a bus accident in Sweden in 1986) and Jason Newsted are former members of the band.",
    "artist_icon": "https://images.kerrangcdn.com/metallica-bio.jpg?auto=compress&fit=crop&w=1200",
    "album_url": ["https://www.metallica.com/on/demandware.static/-/Sites-Metallica-Library/default/dw6503eaa3/images/releases/20150807_213844_7549_752889.jpeg",
                "https://www.nuclearblast.de/static/articles/287/287938-2.jpg/1000x1000.jpg",
                "https://www.nemesisnow.com/media/catalog/product/cache/7c3262bc18147ce5dc018ae87bc5e673/b/4/b4691n9.jpg",
                "https://www.metallica.com/on/demandware.static/-/Sites-Metallica-Library/default/dw978ae3bb/images/releases/20150807_213942_7549_752892.jpeg",
                "https://i.ytimg.com/vi/DqDeH3hwxfw/maxresdefault.jpg",
                "https://www.metallica.com/on/demandware.static/-/Sites-Metallica-Library/default/dw1e473a35/images/releases/20150806_195123_7549_752578.jpeg",
                "https://www.metallica.com/on/demandware.static/-/Sites-Metallica-Library/default/dw1cf2d92d/images/releases/20150806_195123_7549_752579.jpeg",
                "https://townsquare.media/site/366/files/2013/06/stangeralbumcover10.jpg?w=980&q=75",
                "https://www.metallica.com/on/demandware.static/-/Sites-Metallica-Library/default/dw802392ca/images/releases/20150728_153549_7549_750011.jpeg",
                "https://images-na.ssl-images-amazon.com/images/I/71%2BpDTrSdfL._AC_SL1400_.jpg"]
},
{
    "artist_name": "AC DC",
    "artist_genre": ["Hard Rock", "Blues Rock", "Heavy Metal", "Rock and Roll"],
    "artist_members":["Angus Young", "Chris Slade", "Stevie Young", "Axl Rose"],
    "artist_description": "AC/DC are an Australian rock band formed in Sydney in 1973 by Scottish-born brothers Malcolm and Angus Young.[1] Their music has been variously described as hard rock, blues rock, and heavy metal. However, the band themselves describe their music as simply 'rock and roll'.",
    "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2019/07/acdc-highway-to-hell.jpg",
    "album_url": ["https://images-na.ssl-images-amazon.com/images/I/711KOnivDrL._SL1500_.jpg",
                "https://www.rarerecords.com.au/wp-content/uploads/2016/05/IMG_3441.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81FxlF27n8L._SL1500_.jpg",
                "https://cdn.gbposters.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/c/acdc-let-there-be-rock-framed-album-print-1.11.jpg",
                "https://images.genius.com/99e44b06685cec3c3bedfad246190178.1000x1000x1.jpg",
                "https://i.ytimg.com/vi/ikFFVfObwss/maxresdefault.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51kGu9hsYNL._AC_SL1000_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71E23F5%2BWTL._SL1500_.jpg",
                "https://images.genius.com/c629a958a59e3afe27a159b3981f77e8.1000x1000x1.jpg",
                "https://cdn.mos.cms.futurecdn.net/6DKZFeTPoo8wXkjLJ5tNLY.jpg",
                "https://cdn1.bigcommerce.com/server3600/ue6r20oi/products/691/images/1685/IMG_3593__80493.1384724166.1280.1280.JPG?c=2",
                "https://i.ytimg.com/vi/l_7SxoQW11g/maxresdefault.jpg",
                "https://images.squarespace-cdn.com/content/565c1ab5e4b05079e4bfa169/1482281054758-5KZTY0ANUWEZKDW6FMET/ACDC_Ballbreaker.jpg?format=1500w&content-type=image%2Fjpeg",
                "https://img.cdandlp.com/2017/10/imgL/118965919.jpg",
                "https://i.ytimg.com/vi/P2yk0fCO-zc/maxresdefault.jpg",
                "https://img.cdandlp.com/2014/12/imgL/117298187.jpg"]
},
{
    "artist_name":"Guns N' Roses",
    "artist_genre": ["Hard Rock", "Heavy Metal"],
    "artist_members":["Axl Rose", "Duff McKagan", "Slash", "Dizzy Reed", "Richard Fortus", "Frank Ferrer", "Melissa Reese"],
    "artist_description": "Guns N' Roses, often abbreviated as GNR, is an American hard rock band from Los Angeles, California, formed in 1985. When they signed to Geffen Records in 1986, the band comprised vocalist Axl Rose, lead guitarist Slash, rhythm guitarist Izzy Stradlin, bassist Duff McKagan, and drummer Steven Adler. The current lineup consists of Rose, Slash, McKagan, keyboardist Dizzy Reed, guitarist Richard Fortus, drummer Frank Ferrer and keyboardist Melissa Reese.",
    "artist_icon": "https://images.kerrangcdn.com/Guns_N_Roses_promo-1.jpg?auto=compress&fit=crop&w=1200",
    "album_url": ["https://images-na.ssl-images-amazon.com/images/I/91ksS-ioRpL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71%2B2NTohbHL._AC_SL1155_.jpg",
                "https://img.cdandlp.com/2015/10/imgL/117735080.jpg",
                "https://www.clashmusic.com/sites/default/files/field/image/GNR2.jpg",
                "https://townsquare.media/site/295/files/2018/11/Guns-N-Roses-Geffen.jpg",
                "https://miro.medium.com/max/1000/0*x6nor6g-Oe3zNe0P.jpg"]
},
{
    "artist_name": "U2",
    "artist_genre": ["Rock", "Alternative Rock", "Post-Punk"],
    "artist_members":["Bone", "The Edge", "Adam Clayton", "Larry Mullen Jr"],
    "artist_description": "U2 are an Irish rock band from Dublin, formed in 1976. The group consists of Bono (lead vocals and rhythm guitar), the Edge (lead guitar, keyboards, and backing vocals), Adam Clayton (bass guitar), and Larry Mullen Jr. (drums and percussion). Initially rooted in post-punk, U2's musical style has evolved throughout their career, yet has maintained an anthemic quality built on Bono's expressive vocals and the Edge's effects-based guitar textures. Their lyrics, often embellished with spiritual imagery, focus on personal and sociopolitical themes. Popular for their live performances, the group have staged several ambitious and elaborate tours over their career.",
    "artist_icon": "https://www.billboard.com/files/media/U2-press-photo-by-Sam-Jones-2017-billboard-1548.jpg",
    "album_url": ["https://www.post-punk.com/wp-content/uploads/2015/10/peter-rowen-u2-cover-album-boy.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71ZiCQk10lL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/816LHcgjwZL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/715TefHoS%2BL._AC_SL1085_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71nhNKvy%2BfL._AC_SL1059_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51Q5p35aH5L._SL1001_.jpg",
                "https://www.billboard.com/files/media/U2-Achtung-Baby-album-art-billboard-1240.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81r0ClGU6bL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81SpGYq4qiL._AC_SL1400_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fDPDnhHW/SharedImage-79602.jpg?t=9ec8af03ecf7dede5dc6",
                "https://www.itl.cat/pngfile/big/153-1530185_u2-u2-how-to-dismantle-an-atomic-bomb.jpg",
                "https://images.genius.com/e1976130caa4052a75f0c3a46425bac4.1000x1000x1.jpg",
                "https://images.genius.com/528104205bba58533c061cf27550d84c.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1q19PD5MKL._AC_SL1500_.jpg"]
},
{
    "artist_name": "Aerosmith",
    "artist_genre": ["Hard Rock", "Blues Rock", "Rock and Roll", "Glam Metal"],
    "artist_members":["Steven Tyler", "Tom Hamilton", "Joey Kramer", "Joe Perry", "Brad Whitford"],
    "artist_description": "Aerosmith is an American rock band formed in Boston, Massachusetts in 1970. The group consists of Steven Tyler (vocals, keyboards), Joe Perry (guitar), Tom Hamilton (bass), Joey Kramer (drums) and Brad Whitford (guitar). Their style, which is rooted in blues-based hard rock, has come to also incorporate elements of pop rock, heavy metal, and rhythm and blues, and has inspired many subsequent rock artists. They are sometimes referred to as 'the Bad Boys from Boston' and 'America's Greatest Rock and Roll Band'. As a partnership, the primary songwriting team of Tyler and Perry is often collectively known as the 'Toxic Twins'.",
    "artist_icon": "https://www.grammy.com/sites/com/files/styles/news_detail_header/public/aerosmith_person_of_the_year.jpeg?itok=V-7KQwnF",
    "album_url": ["https://images-na.ssl-images-amazon.com/images/I/51f9zSKCniL.jpg"
                "https://images-na.ssl-images-amazon.com/images/I/61GN7Hu4epL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81iR9pMloTL._AC_SL1500_.jpg",
                "https://classicrockreview.files.wordpress.com/2013/05/aerosmith-rocks.jpg",
                "https://townsquare.media/site/295/files/2013/12/aerosmith.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images.genius.com/77dbe69f5f29fdf462658165b7b42a22.953x953x1.jpg",
                "https://townsquare.media/site/295/files/2012/07/aero300.jpg?w=980&q=75",
                "https://townsquare.media/site/295/files/2015/11/Aerosmith-Done-With-Mirrors-Geffen.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81RDzvfVsVL._AC_SL1400_.jpg",
                "https://d24jnm9llkb1ub.cloudfront.net/icpn/00602537156658/00602537156658-cover-zoom.jpg",
                "https://images.genius.com/2313cd84fd9fbb026080bf6658fa4999.945x945x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91RCWPoiacL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71pvGTvudiL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71D-FNL3iFL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81CEQ%2BauLIL._AC_SL1500_.jpg"]
},
{
    "artist_name": "The Who",
    "artist_genre": ["Rock", "Hard Rock", "Power Pop"],
    "artist_members":["Roger Daltrey", "Pete Townshend", "John Entwistle", "Keith Moon", "Doug Sandom", "Kenney Jones"],
    "artist_description": "The Who are an English rock band formed in London in 1964. Their classic line-up consisted of lead singer Roger Daltrey, guitarist and singer Pete Townshend, bass guitarist John Entwistle and drummer Keith Moon. They are considered one of the most influential rock bands of the 20th century, selling over 100 million records worldwide.",
    "artist_icon": "https://upload.wikimedia.org/wikipedia/commons/9/92/Who_-_1975.jpg",
    "album_url": ["https://i.ytimg.com/vi/MgJ9K7cPRKk/maxresdefault.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81UfOIjLKnL._AC_SL1400_.jpg",
                "https://www.thewho.com/wp-content/uploads/1982/09/muisc-studio-album-9.jpg",
                "https://963kklz.com/wp-content/uploads/sites/69/2018/05/TheWho_Tommy_CoverAr_3000DPI300RGB1000145947-e1432393583330.jpg",
                "http://www.progarchives.com/progressive_rock_discography_covers/3091/cover_5101425102016_r.jpg",
                "https://townsquare.media/site/295/files/2013/11/Quadrophenia.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fdZsx7sU/SharedImage-47060.jpg?t=64ddffe216131eeae01c",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fJnDz7sU/SharedImage-47062.jpg?t=bbc801de54e75fbf8eec",
                "https://www.thewho.com/wp-content/uploads/1982/09/muisc-studio-album-3.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71hBf-lAsjL._SL1098_.jpg",
                "https://www.thewho.com/wp-content/uploads/2006/10/muisc-studio-album-1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91nFX1z7pPL._SL1500_.jpg"]
},
{
    "artist_name": "Queen",
    "artist_genre": ["Rock"],
    "artist_members":["Roger Taylor", "Brian May", "Freddie Mercury", "John Deacon"],
    "artist_description": "Queen are a British rock band formed in London in 1970. Their classic line-up was Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), John Deacon (bass guitar), and Roger Taylor (drums, vocals). Their earliest works were influenced by progressive rock, hard rock and heavy metal, but the band gradually ventured into more conventional and radio-friendly works by incorporating further styles, such as arena rock and pop rock.",
    "artist_icon": "https://cdn.britannica.com/83/149183-050-25913164/Queen.jpg",
    "album_url": ["https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f_R2LS6U/SharedImage-53599.jpg?t=071233d688c9ddd18b24",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f3noMS6U/SharedImage-53612.jpg?t=1a8ff15292f3d96da274",
                "https://images-na.ssl-images-amazon.com/images/I/81pIX741PBL._SL1424_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f3C7LS6U/SharedImage-53601.jpg?t=96658919e620ce1dee51",
                "https://cdn.shopify.com/s/files/1/0367/3569/products/QUEEN_A_DAY_AT_THE_RACES_1024x1024.jpeg?v=1441892951",
                "https://images-na.ssl-images-amazon.com/images/I/91GRY6FzEcL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81ppzoGovtL._SL1090_.jpg",
                "http://images.genius.com/b88e93faaa3cb69621b2a93bfdcc763b.1000x1000x1.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fJ0GMS6U/SharedImage-53606.jpg?t=6c07175dae40011f5062",
                "https://images-na.ssl-images-amazon.com/images/I/81B1mbCh4VL._AC_SL1386_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fR-6jyGW/SharedImage-79365.jpg?t=4dee5d0b9ff19afd1947",
                "https://images-na.ssl-images-amazon.com/images/I/91w2m%2Bzw%2BcL._SL1500_.jpg",
                "https://images.genius.com/d2de87a1005e490ecd41ec948fd7e312.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/712rNEMlyQL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71xOjy5FztL._SL1090_.jpg"]
},
{
    "artist_name": "Red Hot Chili Peppers",
    "artist_genre": ["Funk Rock", "Alternative Rock", "Funk Metal", "Rap Rock"],
    "artist_members":["Anthony Kiedis", "Flea", "Chad Smith", "John Frusciante"],
    "artist_description": "Red Hot Chili Peppers are an American rock band formed in Los Angeles in 1983. The group's musical style primarily consists of alternative rock with an emphasis on funk, as well as elements from other genres such as punk rock and psychedelic rock. When played live, their music incorporates elements of jam band due to the improvised nature of many of their performances.",
    "artist_icon": "https://gnrcentral.com/wp-content/uploads/2019/12/red-hot-chili-peppers-john-frusciante-1200x701-1.jpg",
    "album_url": ["https://www.music-bazaar.com/album-images/vol1/74/74404/575691-big/The-Red-Hot-Chili-Peppers-Original-Press-cover.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Zgdo3r1dL._AC_SL1300_.jpg",
                "https://redhotchilipeppers.com/wp-content/uploads/thumbnails/20180924_172012_10286_7796.jpeg",
                "https://images-na.ssl-images-amazon.com/images/I/7131y4Jsd6L._AC_SL1500_.jpg",
                "https://images.squarespace-cdn.com/content/v1/5d79393c390e28547237e9b9/1569253427497-EVLPQ8S7FLDFCMBU2Y6S/ke17ZwdGBToddI8pDm48kBt_kSYLXZe1uHVFCHhHQsN7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmlMqpINHCYwrjchQjceiMlXWRCB61iG5zqb8Ey_N3RWlkswLuE0Oo4CeJB7eQiK8q/blood%2Bsugar%2Bsex%2Bmagik.jpg",
                "https://townsquare.media/site/366/files/2017/09/Red-Hot-Chili-Peppers-One-Hot-Minute.jpg",
                "https://images.genius.com/1dff88c7b88a6c777eca5277dff6a5ab.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81RM%2BS0I9wL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91RXHI%2BDPnL._SL1428_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61G2kxhEpaS._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81CGfXRJkUL._AC_SL1500_.jpg"]
},
{
"artist_name":"Black Sabbath",
"artist_genre":["Heavy Metal"],
"artist_memebers":["Ozzy Osbourne","Tony Iommi", "Geezer Butler", "Cozy Powell"],
"artist_description":"Black Sabbath were an English rock band formed in Birmingham in 1968 by guitarist Tony Iommi, drummer Bill Ward, bassist Geezer Butler and vocalist Ozzy Osbourne. They are often cited as pioneers of heavy metal music. The band helped define the genre with releases such as Black Sabbath (1970), Paranoid (1970), and Master of Reality (1971). The band had multiple line-up changes following Osbourne's departure in 1979, with Iommi being the only constant member throughout its history.",
"artist_icon":"https://townsquare.media/site/366/files/2017/04/Black-Sabbath.jpg",
"album_url": ["https://townsquare.media/site/366/files/2015/07/Black-Sabbath-debut.jpg?w=980&q=75",
            "https://i.ytimg.com/vi/uk_wUT1CvWM/maxresdefault.jpg",
            "https://cdn.mos.cms.futurecdn.net/DDdDtk6XuN7uCA3GaR9eZZ.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/61c30tekbuL._SL1050_.jpg",
            "https://www.indymetalvault.com/wp-content/uploads/2018/11/Black-Sab-SBS.jpg",
            "https://cdn.webshopapp.com/shops/252051/files/182012483/warner-music-group-black-sabbath-sabotage.jpg",
            "https://townsquare.media/site/295/files/2017/08/4-Technical-Ecstasy-Black-Sabbath-1976.jpg?w=980&q=75",
            "https://www.rhino.com/sites/rhino.com/files/styles/square/public/081227946593.sml.jpg.jpg?itok=II07Il_d",
            "https://i.ytimg.com/vi/idn50Xj_CiY/maxresdefault.jpg",
            "https://cdn.mos.cms.futurecdn.net/8yCoECgtKMqRik6FDiNpuY.jpg",
            "https://www.indymetalvault.com/wp-content/uploads/2018/08/1782b45ecdf07e18a56ccbd845bcf012695a0b5c1.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81DnRm90j%2BL._SL1425_.jpg",
            "https://consequenceofsound.net/wp-content/uploads/2017/11/black-sabbath-the-eternal-idol-1920x1920.jpg?quality=80",
            "https://townsquare.media/site/295/files/2013/04/headless.jpg?w=980&q=75",
            "https://i.ytimg.com/vi/WELaLXhE24c/maxresdefault.jpg",
            "https://www.rhino.com/sites/rhino.com/files/styles/square/public/603497850730.sml.jpg?itok=zzaOlYfL",
            "https://i.ytimg.com/vi/qcD1HFD2TUM/maxresdefault.jpg",
            "https://townsquare.media/site/366/files/2017/06/Black-Sabbath-Forbidden.jpg",
            "https://townsquare.media/site/295/files/2013/06/13.jpg?w=980&q=75"]
},
{
"artist_name":"Radiohead",
"artist_genre":["Art Rock", "Alternative Rock", "Electronica", "Experimental Rock"],
"artist_memebers":["Thom Yorke", "Jonny Greenwood", "Colin Greenwood", "Ed O'Brien", "Philip Selway"],
"artist_description":"Radiohead are an English rock band formed in Abingdon, Oxfordshire in 1985. The band consists of Thom Yorke (vocals, guitar, piano, keyboards), brothers Jonny Greenwood (lead guitar, keyboards, other instruments) and Colin Greenwood (bass), Ed O'Brien (guitar, backing vocals) and Philip Selway (drums, percussion). They have worked with producer Nigel Godrich and cover artist Stanley Donwood since 1994.",
"artist_icon":"https://cdn.britannica.com/98/162198-050-6452139D/Radiohead-business-models-British-performers-innovator-Internet-2012.jpg",
"album_url": ["https://images-na.ssl-images-amazon.com/images/I/81wn5pg842L._AC_SL1406_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81XKo5fhRyL._AC_SL1400_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81ni71zIxIL._AC_SL1406_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/71I5kJS%2BdsL._AC_SL1041_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/71B3RDbeiJL._AC_SL1050_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/A1y8IvOibwL._AC_SL1500_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/A1MwaIeBpwL._AC_SL1500_.jpg",
            "https://vignette.wikia.nocookie.net/radiohead/images/3/33/The_king_of_limbs_album_cover.jpg/revision/latest?cb=20181023003242",
            "https://images-na.ssl-images-amazon.com/images/I/815bmGN5LML._AC_SL1200_.jpg"]
},
{
"artist_name":"Lynyrd Skynyrd",
"artist_genre":["Southern Rock", "Blues Rock", "Hard Rock"],
"artist_memebers":["Gary Rossington", "Rickey Medlocke", "Johnny Van Zant", "Michael Cartellone", "Mark Matejka", "Peter Keys", "Keith Christopher"],
"artist_description":"Lynyrd Skynyrd is an American rock band formed in Jacksonville, Florida, in 1964. The group was originally named My Backyard and comprised Ronnie Van Zant (lead vocalist), Gary Rossington (guitar), Allen Collins (guitar), Larry Junstrom (bass guitar) and Bob Burns (drums). The band spent five years touring small venues under a variety of different names and with several lineup changes before finally deciding on 'Lynyrd Skynyrd' in 1969.",
"artist_icon":"https://www.rollingstone.com/wp-content/uploads/2018/06/lynyrd-skynyrd-crash-d345126c-fe0d-4fde-8f0d-a9ce89f8ea3a.jpg",
"album_url":["https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fiMdIy1U/SharedImage-51661.jpg?t=8879d87e3b33ab44c919",
            "https://images-na.ssl-images-amazon.com/images/I/91nSgd2FE6L._AC_SL1443_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/814PsC2%2BpsL._AC_SL1400_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81BI3w5TnUL._AC_SL1400_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/91jX-rp0tzL._SL1500_.jpg",
            "https://i.pinimg.com/originals/48/31/4d/48314dd599d09f2ad22144306ed42901.jpg",
            "https://images.genius.com/2825aeebbfb48c4c65fced93996f0215.953x953x1.jpg",
            "https://images.genius.com/f3fd735b29cd6cea5b6d1b1c9b9fdfc6.953x953x1.jpg",
            "https://img.cdandlp.com/2015/01/imgL/117306083.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81SOmFE35VL._SL1500_.jpg",
            "https://is5-ssl.mzstatic.com/image/thumb/Music62/v4/9c/6b/a3/9c6ba3b3-faa2-abef-5dab-422be7c4acd0/source/1200x1200bb.jpg",
            "https://is5-ssl.mzstatic.com/image/thumb/Music71/v4/61/ca/96/61ca968d-e90a-28b7-0575-800b99806730/source/1200x1200bb.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81Cb0uRe3oL._AC_SL1425_.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81y-RsTl40L._AC_SL1425_.jpg"]
},
{
     "artist_name" : "Eagles",
     "artist_genre" : ["Rock", "Country Rock", "Soft Rock", "Folk Rock"],
     "artist_members": ["Don Henley", "Joe Walsh", "Timothy B. Schmit"],
     "artist_description": "The Eagles are an American rock band formed in Los Angeles in 1971. The founding members were Glenn Frey (guitars, vocals), Don Henley (drums, vocals), Bernie Leadon (guitars, vocals) and Randy Meisner (bass guitar, vocals). With five number-one singles, six number-one albums, six Grammy Awards, and five American Music Awards, the Eagles were one of the most successful musical acts of the 1970s. Their albums Their Greatest Hits (1971–1975) and Hotel California rank first and third, respectively, among the best-selling albums in the United States, with 38 million and 26 million album units in sales.",
     "artist_icon": "https://cdn.britannica.com/50/198850-050-46C563B5/Eagles-Bernie-Leadon-Don-Henley-Glenn-Frey.jpg",
     "album_url": ["https://i.pinimg.com/originals/ec/10/77/ec10777560b73d3303496a136ffbf48e.jpg",
                "https://www.recordsbymail.com/uploads/08-26-12-LPs2/690135.JPG",
                "https://images-na.ssl-images-amazon.com/images/I/71XIex9q9SL._AC_SL1000_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71nDYPeWeWL._SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71SQ5kO9hIL._AC_SL1445_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71jCtXCoeVL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71uOhZyNwvL._AC_SL1200_.jpg"]
   },
   {
     "artist_name" : "Deep Purple",
     "artist_genre" : ["Hard Rock", "Heavy Metal", "Progressive Rock"],
     "artist_members": ["Ian Paice", "Roger Glover", "Ian Gillan", "Steve Morse", "Don Airey", "Ritchie Blackmore"],
     "artist_description": "Deep Purple are an English rock band formed in Hertford in 1968. The band is considered to be among the pioneers of heavy metal and modern hard rock, although their musical approach changed over the years. Originally formed as a psychedelic rock and progressive rock band, the band shifted to a heavier sound in 1970. Deep Purple, together with Led Zeppelin and Black Sabbath, have been referred to as the 'unholy trinity of British hard rock and heavy metal in the early to mid-seventies'. They were listed in the 1975 Guinness Book of World Records as 'the globe's loudest band' for a 1972 concert at London's Rainbow Theatre and have sold over 100 million copies of their albums worldwide.",
     "artist_icon": "https://www.nme.com/wp-content/uploads/2019/05/Webp.net-resizeimage-5.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/61hfoQQlO7L._SL1280_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1kxLSh5W6L._AC_SL1500_.jpg",
                "https://mikeladano.files.wordpress.com/2013/05/purple-lp-front.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71RyvMY5VdL._AC_SL1098_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91t3YBdxgsL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81b3TwFOmtL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71QzHuiPbrL._SL1155_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71zCb18%2BIoL._AC_SL1300_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91H2WmYaezL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71I6KMJuRuL._AC_SL1086_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61br3DQCWIL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/710wkc7FdGL._AC_SL1071_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Vggd9YnmL._AC_SL1280_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81V3m2t0YeL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51C7zXfYceL._AC_SL1000_.jpg",
                "http://www.progarchives.com/progressive_rock_discography_covers/1969/cover_104703042017_r.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91hLo4OrH8L._SL1418_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71bATxj3j4L._SL1319_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61XTNhpwIvL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1gUzeZLuML._AC_SL1500_.jpg"]
   },
   {
     "artist_name" : "Rush",
     "artist_genre" : ["Progressive Rock", "Hard Rock", "Heavy Metal"],
     "artist_members": ["Geddy Lee", "Alex Lifeson", "Neil Peart", "John Rutsey", "Jeff Jones", "Lindy Young", "Joe Perna", "Mitchel Bossi"],
     "artist_description": "Rush was a Canadian rock band consisting of Geddy Lee (bass, vocals, keyboards), Alex Lifeson (guitars), and Neil Peart (drums, percussion). Formed in 1968, the band went through several configurations until arriving at its longest and classic line-up when Peart replaced original drummer John Rutsey in July 1974, two weeks before the group's first tour of the United States.",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/WvyJGdDMTsG8VNTH5ZygRP.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71OdTAZ0Y2L._SL1000_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71X387zpU2L._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81fOjXMjimL._AC_SL1400_.jpg",
                "https://img.cdandlp.com/2018/09/imgL/119291872.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/715ykeQAYcL._AC_SL1076_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/812ScmB3ivL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81JSbij2drL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71khn0s0zmL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81z1-zP1ljL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71IoXzgutTL._AC_SL1082_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81BwtGG7rBL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51rZ137XdsL._AC_SL1423_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81%2BqS4HZ1ML._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/914sVPQbjZL._AC_SL1417_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71kfnpNBQEL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91Qv9jqPvvL._AC_SL1417_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/712OCv9PtSL._AC_SL1442_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91%2BFSdJNbaL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71-FsE%2BDtXL._AC_SL1425_.jpg"]
   },
   {
     "artist_name" : "Pearl Jam",
     "artist_genre" : ["Alternative Rock", "Grunge", "Hard Rock"],
     "artist_members": ["Eddie Vedder", "Mike McCready", "Stone Gossard", "Jeff Ament", "Matt Cameron"],
     "artist_description": "Pearl Jam is an American rock band formed in 1990 in Seattle, Washington. The band's 2020 lineup consists of founding members Eddie Vedder (lead vocals, guitar), Mike McCready (lead guitar), Stone Gossard (rhythm guitar) and Jeff Ament (bass) as well as drummer Matt Cameron, who joined in 1998. Keyboardist Boom Gaspar has also been a session/touring member with the band since 2002. Drummers Jack Irons, Dave Krusen, Matt Chamberlain and Dave Abbruzzese are former members of the band.",
     "artist_icon": "https://www.billboard.com/files/media/Pearl-Jam-2019-cr-Danny-Clinch-billboard-1548.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/813p1x7Vc8L._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/711BOD1NWSL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91lwvIHQSCL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91oBcNHtExL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71y-pLEFGiL._SL1223_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61RVuhZCpIL._SL1500_.jpg",
                "https://i.ytimg.com/vi/7C5U0lMWIYo/maxresdefault.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51U0CZMujdL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81zVLTUKQwL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61H7udj0EsL._AC_SL1500_.jpg",
                "https://pmcvariety.files.wordpress.com/2020/01/shutterstock_editorial_10538463a.jpg?w=1024&h=950"]
   },
   {
     "artist_name" : "The Doors",
     "artist_genre" : ["Psychedelic Rock", "Blues Rock", "Acid Rock"],
     "artist_members": ["Jim Morrison", "Ray Manzarek", "John Densmore", "Robby Krieger"],
     "artist_description": "The Doors were an American rock band formed in Los Angeles in 1965, with vocalist Jim Morrison, keyboardist Ray Manzarek, guitarist Robby Krieger, and drummer John Densmore. They were among the most controversial and influential rock acts of the 1960s, mostly because of Morrison's lyrics and his erratic stage persona, and the group was widely regarded as representative of the era's counterculture.",
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2018/07/the-doors-1968-rough-mix.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81dWUePuUsL._AC_SL1433_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Em52-LVhL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71-smXFocyL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61emBVAQZAL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81UArVyqWbL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71twacm4K1L._AC_SL1144_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81whETcH9zL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A149c5iC%2BBL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/811vFGyPJZL._SL1417_.jpg"]
   },
   {
     "artist_name" : "ZZ Top",
     "artist_genre" : ["Blues Rock", "Boogie Rock", "Hard Rock", "Southern rock"],
     "artist_members": ["Dusty Hill", "Frank Beard", "Billy Gibbons"],
     "artist_description": "ZZ Top (pronounced 'zee zee top') is an American rock trio formed in 1969 in Houston, Texas. The band has, since 1970, consisted of vocalist/guitarist Billy Gibbons (the band's leader, main lyricist and musical arranger), bassist/vocalist Dusty Hill, and drummer Frank Beard. 'As genuine roots musicians, they have few peers', according to critic Michael 'Cub' Koda. 'Gibbons is one of America's finest blues guitarists working in the arena rock idiom [...] while Hill and Beard provide the ultimate rhythm section support.",
     "artist_icon": "https://cdn.britannica.com/95/103095-050-45E47ECB/ZZ-Top-Billy-Gibbons-Frank-Beard-Dusty-2003.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71MR7nIsdpL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81lIxIoMU3L._SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61-1qlDwu4L._SL1426_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81t7dKZdoIL._AC_SL1425_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91xHIRHCtFL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Qv8OOXwcL._SL1079_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71stbFW9t0L._AC_SL1102_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91hXfCFcIOL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71w5LXskh0L._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91RjnZ1peVL._SL1500_.jpg",
                "https://albumartexchange.com/coverart/gallery/zz/zztop_antenna_aubz.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71RXL3DvdVL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71M7qOG0jjL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71ZLl%2BgHIEL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/715jvyfA0YL._AC_SL1200_.jpg"]
   },
   {
     "artist_name" : "The Clash",
     "artist_genre" : ["Punk Rock", "Post-Punk", "New Wave", "Experimental Rock"],
     "artist_members": ["Joe Strummer","Mick Jones", "Paul Simonon", "Topper Headon", "Terry Chimes","Keith Levene", "Rob Harper", "Pete Howard","Nick Sheppard", "Vince White"],
     "artist_description": "The Clash were an English rock band formed in London in 1976 as a key player in the original wave of British punk rock. They have also contributed to the post-punk and new wave movements that emerged in the wake of punk and employed elements of a variety of genres including reggae, dub, funk, ska, and rockabilly. For most of their recording career, the Clash consisted of lead vocalist and rhythm guitarist Joe Strummer, lead guitarist and vocalist Mick Jones, bassist Paul Simonon, and drummer Nicky 'Topper' Headon. Headon left the group in 1982 and internal friction led to Jones' departure the following year. The group continued with new members, but finally disbanded in early 1985.",
     "artist_icon": "https://consequenceofsound.net/wp-content/uploads/2017/04/screen-shot-2017-04-10-at-2-57-27-pm.png",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81Ni3wR4uML._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91U%2B8UJ1%2BvL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71DUFxaoLGL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/913%2BVPxulnL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81A86Lm7%2BKL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71hWzjomrzL._SL1500_.jpg"]
   },
   {
     "artist_name" : "Def Leppard",
     "artist_genre" : ["Hard Rock", "Heavy Metal", "Glam Metal"],
     "artist_members": ["Joe Elliott", "Rick Savage", "Rick Allen", "Phil Collen", "Vivian Campbell"],
     "artist_description": "Def Leppard are an English rock band formed in 1977 in Sheffield as part of the new wave of British heavy metal movement. Since 1992, the band has consisted of Joe Elliott (lead vocals), Rick Savage (bass, backing vocals), Rick Allen (drums, backing vocals), Phil Collen (guitars, backing vocals), and Vivian Campbell (guitars, backing vocals), which has been the band's most stable line-up.",
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-209191-Def-Leppard-Press001.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81hR3tVJYvL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91n55z0DR1L._SL1500_.jpg",
                "https://www.wepluggoodmusic.com/wp-content/uploads/2017/01/Pyromania-Album-Review.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81SqgEk5HiL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/712z--26N4L._SL1085_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91B7yH7n49L._AC_SL1500_.jpg",
                "https://www.udiscovermusic.com/wp-content/uploads/2018/06/Def-Leppard-Euphoria-album-cover-web-optimised-820.jpg",
                "https://townsquare.media/site/295/files/2017/07/X.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://www.defleppard.com/wp-content/uploads/2015/10/DL_yeah.jpg",
                "https://townsquare.media/site/295/files/2018/04/SparkleLounge.jpg?w=980&q=75",
                "https://cdn.mos.cms.futurecdn.net/d2KPdJUGkzVa2nSSDMwJNb.jpg"]
   },
   {
     "artist_name" : "R.E.M.",
     "artist_genre" : ["Alternative Rock", "College Rock", "Folk Rock", "Jangle Pop"],
     "artist_members": ["Bill Berry", "Peter Buck", "Bertis Downs", "Jefferson Holt", "Mike Mills", "Michael Stipe"],
     "artist_description": "R.E.M. was an American rock band from Athens, Georgia, formed in 1980 by drummer Bill Berry, guitarist Peter Buck, bassist Mike Mills, and lead vocalist Michael Stipe. Additionally, many liner notes from the band's albums list attorney Bertis Downs and manager Jefferson Holt as non-musical members. One of the first alternative rock bands, R.E.M. was noted for Buck's ringing, arpeggiated guitar style, Stipe's distinctive vocals and obscure lyrics, Mills's melodic basslines and backing vocals, and Berry's tight, economical drumming.",
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2019/09/rem-flashback.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81nL08pevRL._SL1095_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91QhIWlbk8L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61axEELL32L._SL1045_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71%2BiCCogoUL._SL1064_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81k4nfVJCyL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91k%2BLpdfV%2BL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Ld9ffl63L._AC_SL1200_.jpg",
                "https://images.genius.com/487a7169fadd528f4bb03edfc44711f2.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91LqyCkesiL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61wDC8JqtzL._SL1000_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61VY4WZXdYL._AC_SL1400_.jpg",
                "https://images.genius.com/1d9a12705c88055e0a0694f78766f752.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61QzPvq-rsL._SL1400_.jpg",
                "https://images.genius.com/5e32dab6c788d54e590ce5874c7e58a9.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/712-seCHSfL._AC_SL1400_.jpg"]
   },
   {
     "artist_name" : "Ramones",
     "artist_genre" : ["Punk Rock", "Pop Punk"],
     "artist_members": ["Johnny Ramone", "Dee Dee Ramone", "Joey Ramone", "Tommy Ramone", "Marky Ramone", "Richie Ramone", "Elvis Ramone", "C. J. Ramone"],
     "artist_description": "The Ramones were an American punk rock band that formed in the New York City neighborhood of Forest Hills, Queens in 1974. They are often cited as the first true punk rock group. Despite achieving only limited commercial success initially, the band was highly influential in the United States and the United Kingdom.",
     "artist_icon": "https://www.nme.com/wp-content/uploads/2019/12/Webp.net-resizeimage-3-2.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/9178-Ff7hGL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71ZB%2BI5vCsL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91zph8M19GL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81i--AMD9ZL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81fspHB-XFL._SL1443_.jpg",
                "https://assets.fontsinuse.com/static/use-media-items/31/30633/full-1689x1682/56701cbc/Ramones---Pleasant-Dreams-%28Japan%29---Front.jpeg?resolution=0",
                "https://images-na.ssl-images-amazon.com/images/I/818W4x4VvlL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91%2BY7Ne1iHL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71mkGUmtMzL._AC_SL1094_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91YGZ17%2BrkL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/710nGh6Gc9L._SL1050_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91yffIMRYeL._SL1500_.jpg",
                "https://d1itmove024qgx.cloudfront.net/2c290b8162d9456eca0b615a6c41d95f8bcfc14c.jpg",
                "https://townsquare.media/site/295/files/2016/12/adios1.jpg?w=980&q=75"]
   },
   {
     "artist_name" : "The Police",
     "artist_genre" : ["New Wave", "Raggae Rock", "Post Punk", "Pop Rock"],
     "artist_members": ["Sting", "Andy Summers", "Stewart Copeland", "Henry Padovani"],
     "artist_description": "The Police were a British rock band formed in London in 1977. For most of their history the line-up consisted of primary songwriter Sting (lead vocals, bass guitar), Andy Summers (guitar), and Stewart Copeland (drums, percussion). The Police became globally popular in the late 1970s and early 1980s. Emerging in the British new wave scene, they played a style of rock influenced by punk, reggae, and jazz. Considered one of the leaders of the Second British Invasion of the U.S., in 1983 Rolling Stone labelled them 'the first British New Wave act to break through in America on a grand scale, and possibly the biggest band in the world.' The Police disbanded in 1986, but reunited in early 2007 for a one-off world tour that ended in August 2008.",
     "artist_icon": "https://cdn.wegow.com/media/artists/the-police/the-police-1492562262.85.2560x1440.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71WKJ2WKM1L._SL1400_.jpg",
                "https://cdn.shopify.com/s/files/1/0096/1884/9839/products/The-Police-Reggatta-De-Blanc-Sister-Ray_1024x1024.jpg?v=1570377445",
                "https://images-na.ssl-images-amazon.com/images/I/71lqE-mfPcL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61LsBn8464L._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/815o%2B-4NkVL._SL1200_.jpg"]
   },
   {
     "artist_name" : "Iron Maiden",
     "artist_genre" : ["Heavy Metal"],
     "artist_members": ["Steve Harris", "Dave Murray", "Adrian Smith", "Bruce Dickinson", "Nicko McBrain","Janick Gers"],
     "artist_description": "Pioneers of the new wave of British heavy metal, Iron Maiden achieved initial success during the early 1980s. After several line-up changes, the band went on to release a series of UK and US platinum and gold albums, including 1982's The Number of the Beast, 1983's Piece of Mind, 1984's Powerslave, 1985's live release Live After Death, 1986's Somewhere in Time and 1988's Seventh Son of a Seventh Son. Since the return of lead vocalist Bruce Dickinson and guitarist Adrian Smith in 1999, the band has undergone a resurgence in popularity, with their 2010 studio offering, The Final Frontier, peaking at No. 1 in 28 countries and receiving widespread critical acclaim. Their sixteenth studio album, The Book of Souls, was released on 4 September 2015 to similar success.",
     "artist_icon": "https://www.allthingsloud.com/wp-content/uploads/2017/11/iron-maiden-band-shot.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81XeIxWi6FL._SL1426_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Ih%2B-GSyUL._SL1300_.jpg",
                "https://images.genius.com/45f6688a86df2dd25442f449c73c8b29.894x894x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81bJkvVeOoL._SL1500_.jpg",
                "https://images.genius.com/76ace87e65923ad225efc57c6284ad7a.1000x983x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91qkRQbCEGL._AC_SL1500_.jpg",
                "https://images.genius.com/636a40eb5245b4bd0e4976a155b1ea76.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/813TH-ry3pL._SL1500_.jpg",
                "https://images.genius.com/8e30efe498496d6a56a8867638ed1030.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81MCb0rY%2B-L._AC_SL1401_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81wqQZsZDmL._AC_SL1275_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/810nSIQOLiL._SL1500_.jpg",
                "https://townsquare.media/site/366/files/2016/09/Iron-Maiden-Dance-of-Death.jpg?w=980&q=75",
                "https://images-na.ssl-images-amazon.com/images/I/816DRbjXCVL._AC_SL1300_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81TEBlbygBL._AC_SL1300_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81IoZlwP9AL._AC_SL1500_.jpg"]
   },
   {
     "artist_name" : "Grateful Dead",
     "artist_genre" : ["Rock"],
     "artist_members": ["Jerry Garcia", "Bob Weir", "Phil Lesh", "Bill Kreutzmann", "Mickey Hart", "Ron 'Pigpen' McKernan", "Robert Hunter", "John Perry Barlow", "Tom Constanten", "Keith Godchaux", "Donna Jean Godchaux", "Brent Mydland", "Vince Welnick"],
     "artist_description": "The Grateful Dead was an American rock band formed in 1965 in Palo Alto, California. The band is known for its eclectic style, which fused elements of rock, folk, country, jazz, bluegrass, blues, gospel, and psychedelic rock; for live performances of lengthy instrumental jams; and for its devoted fan base, known as 'Deadheads.' 'Their music,' writes Lenny Kaye, 'touches on ground that most other groups don't even know exists.' These various influences were distilled into a diverse and psychedelic whole that made the Grateful Dead 'the pioneering Godfathers of the jam band world'. The band was ranked 57th by Rolling Stone magazine in its The Greatest Artists of All Time issue.",
     "artist_icon": "https://cdn4.pitchfork.com/longform/373/z0-Grateful-Dead-1960s-Photo-By-Michael-Ochs-Archives-GettyImages-74273862-HEADER.jpg",
     "album_url": ["https://www.billboard.com/files/media/Grateful-Dead-The-Grateful-Dead-50th-Anniversary-Deluxe-Edition-billboard-embed.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81t0IYL1HkL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91v3Hp7yQnL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1IEyNYU2GL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81wWTSyo5IL._SL1500_.jpg",
                "https://external-preview.redd.it/eZij_Otbauh4FI5z6LXQVff4K6fJ5j7VmeZLnowortw.png?auto=webp&s=19d29c7e0f270b3c9bc804fca70bb48a225ec7a0",
                "https://www.washingtonpost.com/rf/image_1484w/2010-2019/WashingtonPost/2015/05/10/Production/Sunday/SunArt/Images/Merlin_15984512.jpg?t=20170517",
                "https://vmp-www.imgix.net/images/51IdAgchLIL.original.jpg?auto=format&w=1700&h=1680",
                "https://images-na.ssl-images-amazon.com/images/I/91sbopYg7UL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71id262wh%2BL._SL1280_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A15sWbO%2BN5L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1x5XqXAYtL._AC_SL1500_.jpg",
                "https://www.rhino.com/sites/rhino.com/files/styles/square/public/603497861255.sml.jpg?itok=MDJWi7SW",
                "https://images-na.ssl-images-amazon.com/images/I/A1McLXKCjgL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91oM2vyXD7L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/9170LF0bhzL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81gm59MSKNL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1n2a5g49KL._SL1500_.jpg",
                "https://cdn.jerrygarcia.com/wp-content/uploads/1987/07/12150731/InTheDark_Cover.jpg",
                "https://cdn.jerrygarcia.com/wp-content/uploads/1989/02/12150746/DylanAndTheDead_Cover.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81cwM1XevqL._SL1500_.jpg",
                "https://cdn.jerrygarcia.com/wp-content/uploads/1990/01/12150658/WithoutANet_Cover.jpg"]
   },
   {
     "artist_name" : "Kiss",
     "artist_genre" : ["Hard Rock", "Heavy Metal", "Shock Rock", "Glam Metal"],
     "artist_members": ["Paul Stanley", "Gene Simmons", "Eric Singer", "Tommy Thayer"],
     "artist_description": "Kiss is an American rock band formed in New York City in January 1973 by Paul Stanley, Gene Simmons, Peter Criss, and Ace Frehley. Well known for its members' face paint and stage outfits, the group rose to prominence in the mid-to-late 1970s with their elaborate live performances, which featured fire breathing, blood-spitting, smoking guitars, shooting rockets, levitating drum kits, and pyrotechnics. The band has gone through several lineup changes, with Stanley and Simmons being the only members to feature in every lineup. The original and best-known lineup consisted of Stanley (vocals and rhythm guitar), Simmons (vocals and bass), Frehley (lead guitar and vocals), and Criss (drums and vocals).",
     "artist_icon": "https://content.fortune.com/wp-content/uploads/2018/09/gettyimages-1036157538.jpg",
     "album_url": ["https://i.pinimg.com/originals/ba/d2/ca/bad2caaaf1ae60cfa279dc12c0cddc7e.jpg",
                "https://www.metalmusicarchives.com/images/covers/kiss-hotter-than-hell-20160906062320.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61ZvqAhWruL._AC_SL1077_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/813yHC4q0yL._SL1428_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81B4ymGsstL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71nHNV%2Bc6RL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71EJ6qtOXBL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61Yqqhdt22L._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61%2BtD%2BNLRzL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71-umQaOd7L._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81EVZX9lQQL._SL1428_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81QzP0gkAlL._AC_SL1417_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81QBr5ABwHL._AC_SL1428_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/810YEVqZ8FL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/811IRvdSeCL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81HlUjgUNJL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71mEQQQMnTL._SL1428_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71l2nm6ji-L._AC_SL1017_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81tEcEl10WL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Bfia1izdL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/812Twyqjz0L._SL1400_.jpg",
                "https://dygtyjqp7pi0m.cloudfront.net/i/24459/22130549_1.jpg?v=8D251365ADF51D0",
                "https://townsquare.media/site/295/files/2019/09/Boom1.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://townsquare.media/site/295/files/2012/09/KISS-Monster-cover.jpg?w=980&q=75"]
   },
   {
     "artist_name" : "Dire Straits",
     "artist_genre" : ["Roots Rock", "Blues Rock", "Pub Rock"],
     "artist_members": ["Mark Knopfler", "John Illsley", "Pick Withers", "David Knopfler", "Alan Clark", "Hal Lindes", "Terry Williams", "Guy Fletcher", "Jack Sonni", "Chris White", "Phil Palmer", "Chris Whitten"],
     "artist_description": "Dire Straits were a British rock band formed in London in 1977 by Mark Knopfler (lead vocals and lead guitar), David Knopfler (rhythm guitar and backing vocals), John Illsley (bass guitar and backing vocals), and Pick Withers (drums and percussion). They were active from 1977 to 1988 and again from 1991 to 1995. Dire Straits are one of the world's best-selling music artists, with album sales of over 100 million. Their first single, 'Sultans of Swing', from their 1978 self-titled debut album, reached the top ten in the UK and US charts. It was followed by hit singles including 'Romeo and Juliet' (1981), 'Private Investigations' (1982), 'Twisting by the Pool' (1983), 'Money for Nothing' (1985), and 'Walk of Life' (1985). Their most commercially successful album, Brothers in Arms (1985), has sold more than 30 million copies; it was the first album to sell a million copies on compact disc, and is the eighth-bestselling album in UK history. According to the Guinness Book of British Hit Albums, Dire Straits have spent over 1,100 weeks on the UK albums chart, the fifth most of all time.",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/QpV8ockPPHcrZFHzQAzWED.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/61MeTu2qYNL._AC_SL1423_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/51bO8MhrcjL._AC_SL1423_.jpg",
                "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Sleeve_of_Making_Movies.svg/1200px-Sleeve_of_Making_Movies.svg.png",
                "https://cdn11.bigcommerce.com/s-rdecee92oy/images/stencil/1280x1280/products/26585/1756022/2wealp47772-large__67063.1544636916.jpg?c=2&imbypass=on",
                "https://images-na.ssl-images-amazon.com/images/I/613DVHvBFmL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Abn1RrhyL._AC_SL1423_.jpg"]
   },
   {
     "artist_name" : "Bon Jovi",
     "artist_genre" : ["Hard Rock", "Glam Metal", "Arena Rock", "Pop Rock"],
     "artist_members": ["Jon Bon Jovi", "David Bryan", "Tico Torres", "Phil X", "Hugh McDonald"],
     "artist_description": "Bon Jovi is an American rock band formed in 1983 in Sayreville, New Jersey. It consists of singer Jon Bon Jovi, keyboardist David Bryan, drummer Tico Torres, guitarist Phil X, and bassist Hugh McDonald.[1] Previous bassist Alec John Such was dismissed in 1994, and longtime guitarist and co-songwriter Richie Sambora left in 2013.",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/LNhM4RE865wz4XuTaVvQt.jpg",
     "album_url": ["https://townsquare.media/site/295/files/2014/01/bon-jovi-1984-debut.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://townsquare.media/site/295/files/2015/03/Mercury2.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/A1Y4BO8RErL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71rlPeoAqUL._AC_SL1078_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/812rXjWvewL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71seEaV6vZL._SL1400_.jpg",
                "https://images.genius.com/b97489d41b1a37986a06806154acba1d.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61-uzSCQypL._AC_SL1050_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMzYzYzdiNTYtNmE3Ny00MDllLWJjNzktMGU3ODNiZjc2NmY0XkEyXkFqcGdeQXVyNTk1NTMyNzM@._V1_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/714qIyMl1iL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71L2ie216rL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91BJbCSW1kL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81pltOJWVxL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81QQ7Xjix0L._AC_SL1400_.jpg",]
   },
   {
     "artist_name" : "Nirvana",
     "artist_genre" : ["Grunge", "Alternative Rock"],
     "artist_members": ["Kurt Cobain", "Krist Novoselic", "Dave Grohl"],
     "artist_description": "Nirvana was an American rock band formed in Aberdeen, Washington in 1987. It was founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic. Nirvana went through a succession of drummers, the longest-lasting and best-known being Dave Grohl, who joined in 1990. Though the band dissolved in 1994 after the death of Cobain, their music maintains a popular following and continues to influence modern rock and roll culture.",
     "artist_icon": "https://www.billboard.com/files/media/nirvana-1991-bw-band-portrait-u-billboard-1548.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71ThvtmT-FL._SL1417_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71VZjASx2kL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/710XKXHIeNL._AC_SL1400_.jpg"]
   },
   {
     "artist_name" : "Judas Priest",
     "artist_genre" : ["Heavy Metal"],
     "artist_members": ["Ian Hill", "Glenn Tipton", "Rob Halford", "Scott Travis", "Richie Faulkner"],
     "artist_description": "Judas Priest are an English heavy metal band formed in West Bromwich, England in 1969. They have sold over 50 million copies of their albums, and are frequently ranked as one of the greatest metal bands of all time. Despite an innovative and pioneering body of work in the latter half of the 1970s, the band had struggled with indifferent record production and a lack of major commercial success or attention until 1980, when they adopted a more simplified sound on the album British Steel.",
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2018/06/priest_jb_1_photoby_justin-borucki-9f8ce263-881b-447f-8e0b-165045f82925.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/819%2BU4DjqkL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71m7EHaIFEL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/815tgL1q4iL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71WfVhFvT1L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71IWm6x7TcL._AC_SL1500_.jpg",
                "https://townsquare.media/site/366/files/2017/04/Judas-Priest-British-Steel-Anniversary.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91dlH0MI%2BRL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81fFofjH%2BkL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81m9KXiKtfL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Pmsq%2BgSJL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/713eANIHjkL._SL1200_.jpg",
                "https://m.media-amazon.com/images/M/MV5BNzE2NDE3NDktZTI5ZS00MGE3LWI2OTItMDcwMGYzNGM4YTg0XkEyXkFqcGdeQXVyNDMxMTc5OTE@._V1_SY1000_SX1000_AL_.jpg",
                "https://lastfm.freetls.fastly.net/i/u/ar0/6870c869e80cd0d454c36b19a10bd029.jpg",
                "https://is4-ssl.mzstatic.com/image/thumb/Music/v4/03/78/8e/03788eeb-e04b-ab0e-b806-30906887ad34/source/1200x1200bb.jpg",
                "https://cdn-s3.allmusic.com/release-covers/500/0001/317/0001317855.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81mPC731nzL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81YfZqdHfvL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81um6dvHukL._AC_SL1500_.jpg"]
   },
   {
     "artist_name" : "Motorhead",
     "artist_genre" : ["Heavy Metal", "Rock and Roll", "Hard Rock", "Speed Metal"],
     "artist_members": ["Ian 'Lemmy' Kilmister", "Larry Wallis", "Lucas Fox", "Phil 'Philthy Animal' Taylor", "'Fast' Eddie Clarke", "Brian 'Robbo' Robertson","Phil 'Wizzo' Campbell","Michael 'Wurzel' Burston", "Pete Gill","Mikkey Dee"],
     "artist_description": "Motorhead were an English rock band formed in June 1975 by bassist, singer, and songwriter Ian 'Lemmy' Kilmister, who was the sole constant member, guitarist Larry Wallis and drummer Lucas Fox. The band are often considered a precursor to the new wave of British heavy metal, which re-energised heavy metal in the late 1970s and early 1980s. Though several guitarists and drummers have played in Motörhead, most of their best-selling albums and singles feature the work of Phil 'Philthy Animal' Taylor on drums and 'Fast' Eddie Clarke on guitars.",
     "artist_icon": "https://www.grammy.com/sites/com/files/styles/image_landscape_hero/public/motorhead-hero-463000304.jpg?itok=OcfwLCTJ",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81SlDntTSAL._SL1500_.jpg",
                "https://images.genius.com/51c433010c4b1415002d6a4a3ab6d4c2.1000x997x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/714%2BCCST4%2BL._AC_SL1200_.jpg",
                "https://www.telegraph.co.uk/content/dam/music/2016/01/07/Up-Front_Motorhead_Ace-of-S_trans%2B%2BqVzuuqpFlyLIwiB6NTmJwfSVWeZ_vEN7c6bHu2jJnT8.jpg",
                "https://www.nuclearblast.de/static/articles/120/120880.jpg/1000x1000.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91sdNLqTibL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81FIy-QvXtL._AC_UL1500_.jpg",
                "https://images.genius.com/42bcc72fac03c8a03ce7867757a74a76.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81TSflKPp6L._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71LnnwhkENL._SL1500_.jpg",
                "https://images.genius.com/556ecab05eee95bf08d173626cfcd52c.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71EOQVAIUjL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71TRRxxp1SL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71NKBItpjnL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71oGlCHRESL._AC_SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61q117X%2BoaL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Y-6rTuXsL._SL1200_.jpg",
                "https://images.genius.com/d79f996e68c168a67c7b70a2cc396111.1000x1000x1.jpg",
                "https://images.genius.com/dffcfebf115602ebe88c7af118df2de3.1000x1000x1.jpg",
                "https://i1.wp.com/theeviljam.co.uk/jamlog/wp-content/uploads/2011/08/motorhead-1.jpg?fit=1200%2C1136&ssl=1",
                "https://townsquare.media/site/295/files/2013/10/Aftershock-300.jpg?w=980&q=75",
                "https://consequenceofsound.net/wp-content/uploads/2015/08/motorhead-bad-magic.jpg?quality=80"]
   },
   {
     "artist_name" : "Whitesnake",
     "artist_genre" : ["Hard Rock", "Blues Rock", "Glam Metal", "Heavy Metal"],
     "artist_members": ["David Coverdale", "Tommy Aldridge", "Reb Beach", "Joel Hoekstra", "Michael Devin", "Michele Luppi"],
     "artist_description": "Whitesnake are a hard rock band formed in England in 1978 by David Coverdale, after his departure from his previous band Deep Purple. Their early material has been compared by critics to the blues rock of Deep Purple, but they slowly began moving toward a more commercially accessible rock style. By the turn of the decade, the band's commercial fortunes changed and they released a string of UK top 10 albums, Ready an' Willing (1980), Come an' Get It (1981), Saints & Sinners (1982) and Slide It In (1984), the last of which was their first to chart in the US and is certified 2x platinum",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/73qpzsuuJ4BVuNxZnPpF9c.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/61IxzEIde4L._SL1280_.jpg",
                "https://townsquare.media/site/295/files/2014/10/Lovehunter.jpg?w=980&q=75",
                "https://images-na.ssl-images-amazon.com/images/I/91RuGARdGNL._SL1500_.jpg",
                "https://i.ytimg.com/vi/8mMiJPhmAIA/maxresdefault.jpg",
                "https://i.ytimg.com/vi/UKxIjCZNQVQ/maxresdefault.jpg",
                "https://www.rhino.com/sites/rhino.com/files/styles/square/public/190295509903.sml.jpg?itok=Vvnp-R7b",
                "https://images.genius.com/69ce0401b78868eae5cf175313d981dc.1000x1000x1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81WhU7zV%2BRL._AC_SL1426_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/816nNqKAxQL._AC_SL1300_.jpg",
                "https://s9.limitedrun.com/images/1176286/Whitesnake---Good-To-Be-Bad.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91%2BFDk9QRPL._SL1412_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/910Zlgf55DL._AC_SL1417_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81oNXdzcNXL._SL1200_.jpg"]
   },
   {
     "artist_name" : "Rainbow",
     "artist_genre" : ["Hard Rock", "Heavy Metal", "Neoclassical Metal"],
     "artist_members": ["Ritchie Blackmore", "Jens Johansson", "David Keith", "Bob Nouveau","Ronnie Romero"],
     "artist_description": "Rainbow (also known as Ritchie Blackmore's Rainbow or Blackmore's Rainbow) are a British rock band led by guitarist Ritchie Blackmore, active from 1975 until 1984, 1993 until 1997, and 2015 until present. They were originally established with Ronnie James Dio's American rock band Elf, but after their first album, Blackmore fired the backing members and continued with Dio until 1979.",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/RvHDUrqS5bnPvHzmi8BJcN.jpg",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71rAUYU-%2BIL._SL1412_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81ZtkTdsgIL._SL1428_.jpg",
                "https://i.ytimg.com/vi/lqC_UMswVlA/maxresdefault.jpg",
                "https://www.indymetalvault.com/wp-content/uploads/2019/07/Rainbow-Down-To-Earth-Indy-Metal-Vault.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91TV7yijvOL._AC_SL1400_.jpg",
                "https://www.vinylnet.co.uk/_assets/_user/images/prods/776057760514_1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91LY3ONDdSL._AC_SL1200_.jpg",
                "https://www.cherryred.co.uk/wp-content/uploads/2017/03/RITCHIE-BLACKMORES-RAINBOW.jpg"]
   },
   {
     "artist_name" : "Europe",
     "artist_genre" : ["Hard Rock", "Glam Metal", "Blues Rock", "Heavy Metal"],
     "artist_members": ["Joey Tempest", "John Norum", "John Leven", "Mic Michaeli", "Ian Haugland"],
     "artist_description": "Europe is a Swedish rock band formed in Upplands Väsby in 1979, by vocalist Joey Tempest, guitarist John Norum, bassist Peter Olsson, and drummer Tony Reno. They got a major breakthrough in Sweden in 1982 by winning the televised competition 'Rock-SM' (Swedish Rock Championships): it was the first time this competition was held, and Europe became a larger success than the competition itself.",
     "artist_icon": "http://rockandrollgarage.com/wp-content/uploads/2017/10/Europe-Band.jpg",
     "album_url": ["https://i.pinimg.com/originals/c9/e8/ff/c9e8fff11a7770827eb8f09b8ae05148.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71I7D%2B3CROL._SL1392_.jpg",
                "https://www.emp-online.com/dw/image/v2/BBQV_PRD/on/demandware.static/-/Sites-master-emp/default/dw14fe6899/images/4/5/0/3/450365.jpg?sfrm=png",
                "https://www.musiconvinyl.com/fotos/3494_foto1_product_xl.jpg",
                "https://img.cdandlp.com/2015/12/imgL/117881937.jpg",
                "https://i.ytimg.com/vi/SM-74QjWjy0/maxresdefault.jpg",
                "https://cont-1.p-cdn.us/images/public/int/3/2/3/1/021823411323_1080W_1080H.jpg",
                "https://is4-ssl.mzstatic.com/image/thumb/Music/v4/46/cb/21/46cb21f9-91db-312d-4463-3bab29674c28/source/1200x1200bb.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81o0eXx8npL._SL1500_.jpg",
                "https://melodicrock.com/sites/default/files/field/image/europe-warofkings.jpg",
                "https://www.paris-move.com/wp-content/uploads/2017/09/EUROPE-1.jpg"]
   },
   {
     "artist_name" : "Thin Lizzy",
     "artist_genre" : ["Hard Rock", "Blues Rock", "Heavy Metal"],
     "artist_members": ["Scott Gorham", "Darren Wharton", "Ricky Warwick", "Damon Johnson", "Scott Travis", "Troy Sanders"],
     "artist_description": "Thin Lizzy are a hard rock band formed in Dublin, Ireland, in 1969. Two of the founding members, drummer Brian Downey and bass guitarist and lead vocalist Phil Lynott, met while still in school. Lynott led the group throughout their recording career of twelve studio albums, writing most of the material. The singles 'Whiskey in the Jar' (a traditional Irish ballad), 'The Boys Are Back in Town' and 'Waiting for an Alibi' were international hits. After Lynott's death in 1986, various incarnations of the band emerged over the years based initially around guitarists Scott Gorham and John Sykes, though Sykes left the band in 2009. Gorham later continued with a new line-up including Downey.",
     "artist_icon": "https://www.ft.com/__origami/service/image/v2/images/raw/ftcms%3Ad55ba18c-2e40-11ea-84be-a548267b914b?source=ig",
     "album_url": ["https://images-na.ssl-images-amazon.com/images/I/71Ev1W6SRlL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81oIlAVK-TL._AC_SL1405_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91poD%2BsEMJL._AC_SL1500_.jpg",
                "https://i.pinimg.com/originals/11/ab/41/11ab41cd96bb3a7b1e821cd9ce01b638.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91csOYb-VOL._AC_SL1500_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.ff1rxL7W/SharedImage-97727.jpg?t=b274561887150488e046",
                "https://i0.wp.com/www.jimfitzpatrick.com/wp-content/uploads/2012/10/JOHNNY-FOX.jpg?fit=1000%2C998&ssl=1",
                "https://images-na.ssl-images-amazon.com/images/I/71LodNmJAyL._AC_SL1419_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61ctApc4YmL._AC_SL1423_.jpg",
                "https://www.jimfitzpatrick.com/wp-content/uploads/2012/10/CHINATOWN.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/711i8YJx7RL._SL1071_.jpg",
                "https://d24jnm9llkb1ub.cloudfront.net/icpn/603497920266/603497920266-cover-zoom.jpg"]
   },
   {
     "artist_name" : "Scorpions",
     "artist_genre" : ["Hard Rock", "Heavy Metal"],
     "artist_members": ["Rudolf Schenker","Klaus Meine", "Matthias Jabs", "Paweł Maciwoda", "Mikkey Dee"],
     "artist_description": "Scorpions are a German rock band formed in 1965 in Hanover by Rudolf Schenker. Since the band's inception, its musical style has ranged from hard rock to heavy metal. The lineup from 1978 to 1992 was the most successful incarnation of the group, and included Klaus Meine (vocals), Rudolf Schenker (rhythm guitar), Matthias Jabs (lead guitar), Francis Buchholz (bass), and Herman Rarebell (drums). The band's only continuous member has been Schenker, although Meine has appeared on all of Scorpions' studio albums, while Jabs has been a consistent member since 1979, and bassist Paweł Maciwoda and drummer Mikkey Dee have been in the band since 2003 and 2016 respectively.",
     "artist_icon": "https://www.gannett-cdn.com/-mm-/d1fd602a4a17c325bcc0465ffa739af790303791/c=0-82-4554-2655/local/-/media/2015/09/06/USATODAY/USATODAY/635771021765582818-Scorpions-Return-To-Forever-c-Oliver-Rath-01-66642154---lo-res.jpg",
     "album_url": ["https://lastfm.freetls.fastly.net/i/u/770x0/390c234104d9448d0ded2d372699ba26.jpg",
                "https://i.pinimg.com/originals/07/fc/1a/07fc1a2ce3630889ec23adcc6d87cf5c.jpg",
                "https://townsquare.media/site/295/files/2015/09/RCA.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://img.cdandlp.com/img_ssl/3106796062-197441-1.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71jYrEO4JtL._SL1200_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91XCQXJyEdL._AC_SL1500_.jpg",
                "https://images.squarespace-cdn.com/content/572a4d599f7266c0b7e6632c/1489947387837-TY8A59WKW1FT6YIA6PDE/scorpions_animal_madnetism_vinyl_front_cover_1024x1024.jpeg?content-type=image%2Fjpeg",
                "https://townsquare.media/site/295/files/2017/03/Blackout.jpeg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81zVbYodPrL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81FacwA04BL._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/7135S7fNNeL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71qh9mxBSrL._AC_SL1400_.jpg",
                "https://www.saintstevensthingery.com/mybackpages/wp-content/uploads/2009/12/scorpionspuref1.jpg",
                "https://img.discogs.com/5Ps0eiOHCl2zlAPRf3C-WwviO7Y=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1941311-1320584613.jpeg.jpg",
                "https://www.music-bazaar.com/album-images/vol4/341/341713/2193051-big/Unbreakable-cover.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71orNViCNHL._AC_SL1500_.jpg",
                "https://img.cdandlp.com/2016/10/imgL/118335549.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Jt0-HbYrL._AC_SL1500_.jpg"]
   },
   {
     "artist_name" : "Van Halen",
     "artist_genre" : ["Hard Rock", "Heavy Metal", "Glam Metal"],
     "artist_members": ["David Lee Roth", "Alex Van Halen", "Eddie Van Halen", "Wolfgang Van Halen"],
     "artist_description": "Van Halen is an American rock band formed in Pasadena, California in 1972. Credited with 'restoring hard rock to the forefront of the music scene', Van Halen is known for its energetic live shows and for the work of its acclaimed lead guitarist, Eddie Van Halen. The band was inducted into the Rock and Roll Hall of Fame in 2007",
     "artist_icon": "https://cdn.mos.cms.futurecdn.net/pfHtAXJFfjJrYmM9jR7Wef.jpg",
     "album_url": ["https://www.rhino.com/sites/rhino.com/files/styles/square/public/VanHalen_CoverHi%2520Res.jpg.jpg?itok=I0xBLeos",
                "https://www.rhino.com/sites/rhino.com/files/styles/square/public/081227954918.sml.jpg?itok=_gNmwVr-",
                "https://townsquare.media/site/295/files/2015/02/Van-Halen-Women-And-Children-First.jpg?w=980&q=75",
                "https://townsquare.media/site/295/files/2016/04/VanHalenFairWarningFrontCover.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Van_Halen_-_Diver_Down.svg/1200px-Van_Halen_-_Diver_Down.svg.png",
                "https://consequenceofsound.net/wp-content/uploads/2019/01/van-halen-1984.png",
                "https://images-na.ssl-images-amazon.com/images/I/81MlBgddxpL._AC_SL1448_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71BhISzzSRL._SL1448_.jpg",
                "https://is5-ssl.mzstatic.com/image/thumb/Music/v4/7b/5f/5f/7b5f5f14-4520-0a41-4355-4f1ad9528ffa/source/1200x1200bb.jpg",
                "https://www.rhino.com/sites/rhino.com/files/styles/square/public/vanhalen_balance.jpg?itok=ZiPvQzxd",
                "https://static.stereogum.com/uploads/2018/03/vhIII-1521217567-compressed.jpg",
                "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-147880-square.jpg?w=960"]
   }
   ]) 