from . import mongo , db
from flask import Blueprint


data = Blueprint('data', __name__)


mongo.db.artist_data.insert_many([{
     "artist_name" : "Led Zeppelin",
     "artist_genre" : ["Hard Rock", "Blues Rock", "Folk Rock", "Heavy Metal"],
     "artist_description": "Led Zeppelin were an English rock band formed in London in 1968. The group consisted of vocalist Robert Plant, guitarist Jimmy Page, bassist/keyboardist John Paul Jones, and drummer John Bonham. With their heavy, guitar-driven sound, Led Zeppelin are regularly cited as one of the progenitors of heavy metal, although their style drew from a variety of influences, including blues and folk music.",
     "artist_members": ["Robert Plant", "Jimmy Page", "John Paul Jones", "John Bonham"],
     "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2012/11/LedZeppelin.jpg",
     "album_url": ["https://api.time.com/wp-content/uploads/2014/06/ledzep.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71mKCivU38L._AC_SL1200_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71whCYj9mtL._AC_SL1200_.jpg",
                    "https://www.thisdayinmusic.com/wp-content/uploads/2018/05/led-zeppelin-iv.jpg",
                    "https://cdn.mos.cms.futurecdn.net/2HZ8HfhPdzGjzxFSjjnLK5.jpg",
                    "https://img.cdandlp.com/2018/01/imgL/119046525.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/71Uy9%2Bv4W8L._SL1057_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/712vB0qw1IL._AC_SL1218_.jpg",
                    "https://images-na.ssl-images-amazon.com/images/I/81QZqBpmuBL._AC_SL1401_.jpg"]
   },
   {
    "artist_name": "The Beatles",
    "artist_genre":["Rock", "Pop"],
    "artist_members":["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"],
    "artist_description": "The Beatles were an English rock band formed in Liverpool in 1960. With a line-up comprising John Lennon, Paul McCartney, George Harrison and Ringo Starr, they are commonly regarded as the most influential band of all time. The group were integral to the development of 1960s counterculture and popular music's recognition as an art form.",
    "artist_icon": "https://miro.medium.com/max/12106/1*zdmpyfSSsyJbUWP3wU0onw.jpeg",
    "album_url": ["https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/PleasePleaseMe_1.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_463.jpg",
                   "https://images-na.ssl-images-amazon.com/images/I/71QKKZZABLL.jpg",
                   "https://www.popsike.com/pix/20171220/232603676076.jpg",
                   "https://www.beatlesbible.com/wp/media/canada_twist_and_shout.jpg",
                   "https://www.beatlesbible.com/wp/media/usa_beatles-second-album-960x960.jpg",
                   "https://images.genius.com/7d93682f1062d894ee6b75d9b42c519e.1000x1000x1.jpg",
                   "https://i.pinimg.com/originals/1e/44/f4/1e44f4c45fd1794b119ff5b77d214956.jpg",
                   "https://www.beatlesbible.com/wp/media/something_new-960x960.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/BeatlesForSale_1.jpg",
                   "https://www.beatlesbible.com/wp/media/usa_beatles-65.jpg",
                   "https://i.pinimg.com/originals/b8/af/f5/b8aff55f6fd9973b9e0104e4e11e2618.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_447.jpg?itok=H9p6ueVD&timestamp=1354886431",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_450.jpg",
                   "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-245574-The-Beatles-Yesterday-Today.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_449.jpg?itok=vEdbQ8AQ&timestamp=1354886431",
                   "https://images-na.ssl-images-amazon.com/images/I/91l7ue6WOhL._AC_SL1500_.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/Magical_0.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_442.jpg?itok=gJ2GzgoW&timestamp=1354886431",
                   "https://images-na.ssl-images-amazon.com/images/I/91IaG%2BLrzmL._AC_SL1500_.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_441.jpg",
                   "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/media_responsive_widest/public/tile/image/original_459.jpg?itok=OGwy4GrW&timestamp=1354886431"]
},
{
    "artist_name": "The Rolling Stones",
    "artist_genre": ["Rock", "Blues", "Rock and Roll"],
    "artist_members":["Mick Jagger", "Keith Richards", "Ronnie Wood", "Charlie Watts"],
    "artist_description": "The Rolling Stones were at the forefront of the British Invasion of bands that became popular in the United States in 1964 and were identified with the youthful and rebellious counterculture of the 1960s. Rooted in blues and early rock and roll, the band started out playing covers but found more success with their own material; songs such as '(I Can't Get No) Satisfaction' and 'Paint It Black' became international hits, and Aftermath (1966) – their first entirely original album – has been considered the most important of the band's formative records",
    "artist_icon": "https://static.spin.com/files/2019/11/GettyImages-113914585-1573422723-1387x1000.jpg",
    "album_url":["https://images-na.ssl-images-amazon.com/images/I/71smgDG%2BwmL._SL1400_.jpg",
                "https://merchbar.imgix.net/product/vinylized/upc/02/018771940210.jpg?w=1280&h=1280&quality=60&auto=compress%252Cformat",
                "https://img.cdandlp.com/2018/03/imgL/119086142.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71VRIposvFL._AC_SL1081_.jpg",
                "https://cdn.shopify.com/s/files/1/1110/4380/products/out_1_1024x1024.jpg?v=1469913732",
                "https://images-na.ssl-images-amazon.com/images/I/71nZ93p2r6L._SL1052_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/61NRkoLaVBL._SL1050_.jpg",
                "https://img.cdandlp.com/2018/01/imgL/119037544.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/A1XVfdlfEpL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81oDiFJodeL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91RtFs10t2L._SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81nq2oxgpOL._AC_SL1417_.jpg",
                "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fLCv-HDV/SharedImage-57461.jpg?t=8e089894710294b6de51",
                "https://img.cdandlp.com/2015/12/imgL/117795678.jpg",
                "https://i0.cdn.hhv.de/catalog/shop_detail_zoom/00550/550930.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81-skWr98xL._SL1400_.jpg",
                "https://classicrockreview.files.wordpress.com/2013/03/115380777.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71FS5m9frSL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/91-xbEW-OwL._AC_SL1500_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81hNwsqlPxL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/71Azu70DcmL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81Fw-KkZIzL._AC_SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81kY1ASWjgL._SL1400_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81wZCql9M6L._AC_SL1400_.jpg",
                "https://townsquare.media/site/295/files/2015/09/Rolling-Stones-Bigger-Bang.jpeg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://townsquare.media/site/295/files/2016/11/stones1.jpg?w=980&q=75"]
},
{
    "artist_name": "Pink Floyd",
    "artist_genre": ["Pink Floyd", "Progressive Rock", "Experimental Rock"],
    "artist_members":["Nick Mason","Roger Waters","Richard Wright","Syd Barrett","David Gilmour"],
    "artist_description": "Pink Floyd were an English rock band formed in London in 1965. Gaining a following as a psychedelic pop group, they were distinguished for their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows, and became a leading band of the progressive rock genre. They are one of the most commercially successful and influential bands in popular music history.",
    "artist_icon": "https://www.rollingstone.com/wp-content/uploads/2018/06/pink-floyd-1973-32d763d9-8deb-4cd8-a287-92ae0de7df3a.jpg",
    "album_url": ["https://images-na.ssl-images-amazon.com/images/I/81Kzmcv5wXL._AC_SL1300_.jpg",
                "https://images.genius.com/12d2417b62f7f315f2bd8d8aea445f8a.1000x1000x1.jpg",
                "https://townsquare.media/site/295/files/2014/08/Pink-Floyd-More.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81-Joj09kIL._SL1300_.jpg",
                "https://townsquare.media/site/295/files/2015/10/Pink-Floyd-Atom-Heart-Mother.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81hBOBD242L._SL1500_.jpg",
                "https://townsquare.media/site/295/files/2012/06/Pink-Floyd-Obscured-by-Clouds-Photo.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                "https://images-na.ssl-images-amazon.com/images/I/81aTawcGdmL._AC_SL1500_.jpg",
                "https://miro.medium.com/max/1000/1*Aad3rcP6yKOj3LgWqx75gA.jpeg",
                "https://i2.wp.com/liveforlivemusic.com/wp-content/uploads/2017/01/animalspigs.jpg?fit=1920%2C1080&ssl=1",
                "https://images-na.ssl-images-amazon.com/images/I/715jbEtLNcL._AC_SL1489_.jpg",
                "https://consequenceofsound.net/wp-content/uploads/2017/06/pink-floyd-the-final-cut.jpg?quality=80",
                "https://images-na.ssl-images-amazon.com/images/I/81NuMz4OsrL._AC_SL1310_.jpg",
                "https://images-na.ssl-images-amazon.com/images/I/81fvyZlrbAL._AC_SL1300_.jpg",
                "https://i.ytimg.com/vi/RFXBlS0KsHU/maxresdefault.jpg"]
}
   ]) 